language: elm
elm: 0.19.1
elm-test: 0.19.0-rev6
elm-format: 0.8.3
node_js: 'node' # Latest stable.

os:
  - linux

env:
  - PATH=$TRAVIS_BUILD_DIR/node_modules/.bin:$TRAVIS_BUILD_DIR/sysconfcpus/bin:$PATH

cache:
  directories:
    - sysconfcpus

before_install:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

install:
  - node --version
  - npm --version
  - npm install -g elm-verify-examples@5.0.0 elm-review

script:
  - elm-format --validate src
  - elm make
  - ./execute-tests
  - elm-review